# Generated by Django 5.0.2 on 2024-02-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstexpense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='firstexpenses',
            options={'verbose_name_plural': 'FirstExpenses'},
        ),
    ]
